spring:
  application:
    name: spring-boot-3
  profiles:
    active: local

  # 404 NoHandlerFoundException for controller advice
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false